### ISSUE TITLE
Hi, How should I run the program?

### ISSUE THREAD

**Issue by longfly2** [mesuvash/LRec#1]
Hi, I have read your paper, and it's a really great work! However, when I have read the paper, I try to run the program , but I can not run right. So, I need your help, could you please write a tutorial (especially about the test dataset, how to load the dataset?)

**Comment by mesuvash** [comment]
I shall update a tutorial this weekend.

**Comment by mesuvash** [comment]
I have added Ipython notebook to help you get started.
